language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
script:
- set -e
- mvn test -B
- mvn cobertura:cobertura
env:
  global:
  - MAVEN_OPTS="-Xmx256m"
  - JAVA_OPTS="-Xmx256m"
jdk:
- oraclejdk8
after_success:
- "bash <(curl -s https://codecov.io/bash)"