language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - MAVEN_OPTS="-Xmx256m"
  - JAVA_OPTS="-Xmx256m"
jdk:
- oraclejdk8

script:
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
